//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica_Lester.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblRFID_CodiCaptEmbarques
    {
        [Display(Name = "#")]
        public int id { get; set; }

        [Display(Name = "RFID")]
        public string codebar { get; set; }

        [Display(Name = "Acronimo")]
        public string acronimo { get; set; }

        [Display(Name = "Hora de lectura")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> fechaLectura { get; set; }

        [Display(Name = "Objeto Referencia")]
        public string objReferencia { get; set; }

        [Display(Name = "Tipo")]
        public int tipo { get; set; }

        [Display(Name = "Viaje")]
        public string Viaje { get; set; }
    }
}
